### PR TITLE
Multiple fixes for docs and settings

### PR DESCRIPTION
**Pull request by clintonb**
@rlucioni @jimabramson @bderusha @peter-fogg

### CODE REVIEW

**Comment by jimabramson** [comment]
:+1:

**Comment by bderusha** [comment]
:+1:

**Comment by rlucioni** [comment]
:+1:

**Comment by feanil** [comment]
:+1:

**Comment by clintonb** [comment]
The docs fixes seem to affect coverage for ecommerce. Will update this PR once I have a fix.

**Comment by clintonb** [comment]
Disregard the note about docs changes affecting coverage. I did not make that change in this repo.

**Pull request merged**
